version: "3.9"
services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-risn}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-risn}
      POSTGRES_DB: ${POSTGRES_DB:-risn}
    ports: ["5432:5432"]
    volumes:
      - ./docker-data/postgres:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]
  otel-collector:
    image: otel/opentelemetry-collector:0.104.0
    command: ["--config=/etc/otel-collector-config.yml"]
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml
    ports:
      - "4317:4317" # OTLP gRPC
  jaeger:
    image: jaegertracing/all-in-one:1.57
    ports:
      - "16686:16686"
    environment:
      - COLLECTOR_OTLP_ENABLED=true

# To run: docker compose -f infra/docker-compose.yml up -d
